version: "3.4"

services:
  master:
    image: satheeshpandianj/jmetermaster
    container_name: master
    tty: true
    hostname: master
    networks:
      - sats
  slave:
    image: satheeshpandianj/jmeterslave
    tty: true
    networks:
      - sats

  influxdb:
    image: influxdb:1.8
    networks:
      - sats
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
  grafana:
    image: grafana/grafana:latest
    networks:
      - sats
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

networks:
  sats:
    driver: bridge
