# Use vinsdocker base image
FROM satsjmeter.azurecr.io/jmeter:jmeterbase
MAINTAINER SATHEESH PANDIAN JEGANATHAN <satheeshpandianj@gmail.com>

# Ports to be exposed from the container for JMeter Master
EXPOSE 60000