# Use vinsdocker base image
FROM satheeshpandianj/jmeterbase
MAINTAINER SATHEESH PANDIAN JEGANATHAN <satheeshpandianj@gmail.com>

# Ports to be exposed from the container for JMeter Master
EXPOSE 60000